# This needs to be in your library source code repository!

apiVersion: v1
kind: Pod
spec:
  containers:
  -   name: javelin-common
      image: mrllus2cbacr.azurecr.io/merrillcorporation/cloudbees-ephemeral-agents:mongo-jdk11
      resources:
        limits:
          cpu: "1"
          memory: "6Gi"
        requests:
          cpu: "0.5"
          memory: "1Gi"
      command:
      - cat
      tty: true
  imagePullSecrets:
  -   name: cbacr