apiVersion: v1
kind: Pod
spec:
  containers:
  -   name: javelin-common
      image: mrllus2cbacr.azurecr.io/merrillcorporation/cloudbees-ephemeral-agents:api-smoke-testing-1.0
      tty: true
      command:
      - cat