# This needs to be in your library source code repository!

apiVersion: v1
kind: Pod
spec:
  containers:
  -   name: javelin-common
      image: mrllus2cbacr.azurecr.io/merrillcorporation/cloudbees-ephemeral-agents:mongo
      command:
      - cat
      tty: true
  imagePullSecrets:
  -   name: cbacr