apiVersion: v1
kind: Pod
spec:
  containers:
  - name: ruby-node
    image: mrllus2cbacr.azurecr.io/merrillcorporation/cloudbees-ephemeral-agents:sup1-node
    tty: true
    resources:
      limits:
        cpu: "1"
        memory: "6Gi"
      requests:
        cpu: "0.5"
        memory: "1Gi"
    command:
    - cat
  imagePullSecrets:
  -   name: cbacr