apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cfoundry
    image: mrllus2cbacr.azurecr.io/merrillcorporation/cloudbees-ephemeral-agents:atlassian-node-jfrog
    resources:
      limits:
        cpu: "1"
        memory: "6Gi"
      requests:
        cpu: "0.5"
        memory: "1Gi"
    tty: true
    command:
    - cat
  imagePullSecrets:
  - name: cbacr
